#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line
a=1

while [ $a -le 10 ]
do
    if [ $a -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi

    (( a+=1))
done
