#!/usr/bin/env bash

a=1

while [ $a -le 20 ]
do
    case $a in
        4) 
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $a
            ;;
    esac

    (( a+=1))
done